In [23]:
def prime():
    print('------ reuai ------')

In [24]:
prime()

------ reuai ------


In [1]:
def potencia(n):
    return n * n

print(potencia(10))

100


In [2]:
def div(m,n):
    return m * (1/n)

print(div(25,5))

5.0


In [13]:
# dados: 
x = [0,9,18,27,36,45,54]
y = -12

print(sum(x))
prime()
print(max(x))
prime()
print(min(x))
prime()
print(abs(y))
prime()
z = (float(input('Digite um número decimal: ')))
prime()
print(round(z))

189
------ reuai ------
54
------ reuai ------
0
------ reuai ------
12
------ reuai ------


Digite um número decimal:  12.87


------ reuai ------
13


In [16]:
from statistics import *

# usar esse formato para importar todas as funções da biblioteca statistics

t = [1,1,2,3,5,8,13,21,34,55]

print('média:', mean(t))
print('moda:',mode(t))
print('mediana:',median(t))
print('variância:',variance(t))
print('desvio padrão:',stdev(t))

# outra forma seria 'import statistics as est' e depois est.mean(t), etc... 
# mas, importar todas as formulas da biblioteca já facilita muito a notação. 

média: 14.3
moda: 1
mediana: 6.5
variância: 316.6777777777778
desvio padrão: 17.795442612584207


In [22]:
from numpy import *

x = random.randn(3,3)
print(x)

# plotei uma matriz 3x3 de valores randômicos de -1 até 1 (?). 
# antes, eu teria que escrever 'import numpy as np' e depois np.random.randn().

[[ 1.36706757 -0.13498845  0.47532206]
 [ 1.01224178 -1.04354814  0.49432795]
 [-0.08427386  0.01262928 -0.40821223]]
