In [8]:
import numpy as np

1) Dada a matriz abaixo, construa uma estrutura de repetição para percorrer e somar todos os elementos da matriz

    matriz = np.array([[3, 4, 1],
                       [3, 1, 5]])

In [18]:
m1 = np.array([[3, 4, 1],[3, 1, 5]])

soma_l1 = 0
soma_l2 = 0

for i in range(0,2):
    soma_l1 = m1[0,0] + m1[0,i] + m1[0,i+1]

for n in range(0,2):
    soma_l2 = m1[1,0] + m1[1,i] + m1[1,i+1]

print(soma_l1)
print('---------')
print(soma_l2)
print('---------')
print('A soma dos elementos é: ',soma_l1 + soma_l2)

8
---------
9
---------
A soma dos elementos é:  17


In [21]:
m1 = np.array([[3, 4, 1],[3, 1, 5]])

dim_m1 = m1.shape
print(dim_m1)
print('---------')
      
soma = 0 

for i in range(dim_m1[0]):
    for j in range(dim_m1[1]):
        soma = soma + m1[i][j]

print('A soma dos elementos é:', soma)
    

(2, 3)
---------
A soma dos elementos é: 17


In [33]:
# Utilizando np.array() crie:
# 1 array unidimensional "vetor"
# 1 array de duas dimensões "matrix"
# 1 array de três dimensões

v1 = np.arange(5)
matrix = np.array([[1,2,3],[3,2,1]])
m2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(v1)
print(matrix)
print(m2)
print('-------------')

# Liste os atributos de todos os arrays criados anteriormente
# número de dimensões, tipo de dado, tamanho

print('Sobre o vetor 1:',v1.shape,v1.dtype)    
print('Sobre a matrix:',matrix.shape,matrix.dtype)
print('Sobre a matriz 3d:',m2.shape,m2.dtype)
print('-------------')

# Crie um array de números 1 de shape (10, 2)
uns0 = np.ones(10)
uns1 = np.ones(10)
uns = np.vstack([[uns0],[uns1]])

print(uns)
print('-------------')

# Crie um array de zeros de shape (5, 4, 3)

zero = np.zeros((5,4,3))
print(zero)
print('-------------')

# Crie um array com um range entre 0 e 100 e com step 3

rang = np.arange(0,100,3)
print(rang)
print('-------------')

# Crie um array random (com elementos aleatórios) entre 0 e 10 de tamanho (7, 2)

aleat = 10*(np.random.random((7,2)))
print(aleat)
print('-------------')

# Crie um array random float com elementos entre 0 e 1 com shape (5, 3)

aleat = np.random.random((5,3))
print(aleat)
print('-------------')

# Utilize  o seed com valor 42 e crie um array de números aleatórios entre 0 e 10 de tamanho (5, 3)
     

# Selecione o primeiro elemento do último array que você criou

prime = aleat[0,0]
print(prime)
print('-------------')

# Selecione a primeira linha do último array criado

prime1 = aleat[0,:]
print(prime1)
print('-------------')

# Selecione do primeiro até o segundo elemento da primeira linha do último array criado

prime = aleat[0,0:2]
print(prime)
print('-------------')

# Crie um novo array usando 'ones' com shape (3, 5)

unss = np.ones((5,3))
print(unss)
print('-------------')

# Subtraia o novo array de outro com dados aleatórios e armazene o resultado em uma variável chamada 'matrix'
     
matrix1 = unss - aleat
print(matrix1)
print('-------------')

# Encontre a média usando 'np.mean()' do valores no novo array chamado 'matrix'

mediabooger = np.mean(matrix1)
print(mediabooger)
print('-------------')

# Faça a transposição da 'matrix', usando o método '.T'
     
transaposta = matrix1.T
print(transaposta)


[0 1 2 3 4]
[[1 2 3]
 [3 2 1]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
-------------
Sobre o vetor 1: (5,) int64
Sobre a matrix: (2, 3) int64
Sobre a matriz 3d: (3, 3) int64
-------------
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
-------------
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
-------------
[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]
-------------
[[2.65699087 1.96672177]
 [0.43788784 9.19558958]
 [0.37992512 5.68197839]
 [2.94225841 4.64520608]
 [6.31862006 7.96011157]
 [8.4340108  5.01271316]
 [9.87918572 9.77195776]]
-------------
[[0.18090012 0.67449242 0.11459898]
 [0.89493649 0.58399815 0.10955753]
 [0.9219368  0.47369552 0.23447949]
 [0.70474109 0.68684307 0.83645377]
 [0.37

3) Um professor registrou as notas de 8 alunos em duas provas:

import numpy as np

notas = np.array([
    [7.5, 8.0],
    [6.0, 7.0],
    [9.0, 8.5],
    [5.5, 6.0],
    [8.0, 9.0],
    [4.0, 5.5],
    [7.0, 7.5],
    [9.5, 9.0]
])


Calcule a média de cada aluno.

Calcule a média de cada prova.

Determine quantos alunos ficaram com média ≥ 7.

In [41]:
notas = np.array([[7.5, 8.0],[6.0, 7.0],[9.0, 8.5],[5.5, 6.0],[8.0, 9.0],[4.0, 5.5],[7.0, 7.5],[9.5, 9.0]])

print(notas)
print('---------')

# média de cada aluno: 

aluno1 = (notas[0,0]+ notas[0,1])/2
aluno2 = (notas[1,0]+ notas[1,1])/2
aluno3 = (notas[2,0]+ notas[2,1])/2
### anotação só para pegar o padrão da sequência. 

for i in range(0,8):
    media = (notas[i,0] + notas[i,1])/2
    print('a média do aluno', i+1, 'é:', media)
print('-------------------')

# média de cada coluna da tabela/matriz:

p1 = notas[:,0]
p2 = notas[:,1]
media_p1 = np.mean(p1)
media_p2 = np.mean(p2)
soma_p1 = media_p1*len(p1)
soma_p2 = media_p2*len(p2)

print('A média na prova 1 foi:', media_p1)
print('A média na prova 2 foi:', media_p2)
print('soma 1:',soma_p1,'soma 2:',soma_p2)
print('---------')

# número de alunos com média >= 7:

media_maior_7 = []

for i in range(0,8):
    media = (notas[i,0] + notas[i,1])/2
    if media >= 7:
        media_maior_7.append(media)
    else:
        continue

numero_alunos = len(media_maior_7)

print('o número de alunos com média maior que 7 é:', numero_alunos)    
print('-------------------')


[[7.5 8. ]
 [6.  7. ]
 [9.  8.5]
 [5.5 6. ]
 [8.  9. ]
 [4.  5.5]
 [7.  7.5]
 [9.5 9. ]]
---------
a média do aluno 1 é: 7.75
a média do aluno 2 é: 6.5
a média do aluno 3 é: 8.75
a média do aluno 4 é: 5.75
a média do aluno 5 é: 8.5
a média do aluno 6 é: 4.75
a média do aluno 7 é: 7.25
a média do aluno 8 é: 9.25
-------------------
A média na prova 1 foi: 7.0625
A média na prova 2 foi: 7.5625
soma 1: 56.5 soma 2: 60.5
---------
o número de alunos com média maior que 7 é: 5
-------------------


4) A produção diária (em unidades) de três máquinas durante 7 dias:

P = np.array([
    [120, 130, 125],
    [118, 128, 122],
    [125, 135, 130],
    [130, 138, 133],
    [128, 134, 129],
    [127, 132, 128],
    [129, 136, 131]
])


Qual máquina teve maior produção média?

Qual foi a produção total da fábrica na semana?

Encontre o dia de maior produção total.

In [85]:
prod = np.array([[120, 130, 125],[118, 128, 122],[125, 135, 130],[130, 138, 133],[128, 134, 129],[127, 132, 128],[129, 136, 131]])
print(prod)
print('----------------')

# máquina com maior produção média:

media1 = media2 = media3 = soma1 = soma2 = soma3 = 0
prod_media = []
prod.shape

for i in range(prod.shape[0]):
    soma1 = soma1 + prod[i,0]
    media1 = soma1/prod.shape[0]
for j in range(prod.shape[0]):
    soma2 = soma2 + prod[j,1]
    media2 = soma2/prod.shape[0]
for k in range(prod.shape[0]):
    soma3 = soma3 + prod[k,2]
    media3 = soma3/prod.shape[0]
### usei o prod.shape[0] ao invés de só escrever 7, porque isso generaliza o 
### processo, e funciona caso o número de dias aumente. 
    
prod_media.append(media1)
prod_media.append(media2)
prod_media.append(media3)

if media1 == max(prod_media):
    print('A máquina com maior produção média é a Máquina 01.')
elif media2 == max(prod_media):
    print('A máquina com maior produção média é a Máquina 02.')
elif media3 == max(prod_media):
    print('A máquina com maior produção média é a Máquina 03.')

print('----------------')

# Qual foi a produção total da fábrica na semana?    

soma = 0
prod.shape

for i in range(prod.shape[0]):
    for j in range(prod.shape[1]):
        soma = soma + prod[i,j]
### usar essa fórmula percorrendo i e j usando for sempre que precisar percorrer
### todos os elementos de uma matriz. 

print('A produção total da fábrica nessa semana é:', soma, 'unidades.')
print('----------------')

# Encontre o dia de maior produção total.

souma = j = 0
producoes_diarias = {}

for j in range(0,7):
    souma = prod[j,0] + prod[j,1] + prod[j,2]
    producoes_diarias['dia',j+1] = souma

dia_mais_produtivo = max(producoes_diarias.values())

for chave, valor in producoes_diarias.items():
    if valor == dia_mais_produtivo:
        print('O dia mais produtivo foi o',chave,'.')

### cara, nessa aqui eu fui gigantesco!!! no primeiro bloco, descrevi a soma de 
### cada linha em função das colunas. Depois, guardei os valores encontrados em 
### cada em um FUCKING DICIONÁRIO, para associar o dia ao valor. Depois, encontrei
### o valor máximo com o max e o values e por último, tive que pedir uma ajudinha
### do chat para associar o valor encontrado à chave correspondente, porque 
### aparentemente, o dicionário só consegue associar uma chave a um valor. 


[[120 130 125]
 [118 128 122]
 [125 135 130]
 [130 138 133]
 [128 134 129]
 [127 132 128]
 [129 136 131]]
----------------
A máquina com maior produção média é a Máquina 02.
----------------
A produção total da fábrica nessa semana é: 2708 unidades.
----------------
O dia mais produtivo foi o ('dia', 4) .


5) Considere o sistema:

2x+y=5
x+3y=6
	


Monte as matrizes 
𝐴 e b.

Resolva o sistema usando np.linalg.solve.

Verifique a solução multiplicando Ax.

In [ ]:
# essa aqui é bem interessante, mas fica para outro dia. 