NumPy - MATRIZES pt.1

In [1]:
import numpy as np

# numpys criam matrizes porra lets fucking goooooooooo

In [40]:
vet1 = np.array([11,22,33.5,44,55,66])
print(vet1)
print(vet1.dtype)

#float 64 bits, porque tem um número decimal no meio da lista.

[11.  22.  33.5 44.  55.  66. ]
float64


In [47]:
mat1 = np.array([[11,22,33],[5,10,15],[-1,-2,-3]])
print(mat1)
print('--------')
print(mat1.dtype)

[[11 22 33]
 [ 5 10 15]
 [-1 -2 -3]]
--------
int64


In [24]:
# matriz de zeros:

vet2 = np.zeros(3)

print(vet2)

# multiplicação matricial é dada por @: 
mult1 = mat1 @ vet2

print(mult1)

# a multiplicação matricial funciona se, e somente se, o número de linhas 
# da primeira é igual ao número de linhas da segunda. 

[0. 0. 0.]
[0. 0. 0.]


In [45]:
# operações com escalares são feitas termo a termo:

print (mat1)
print('-----------')
print (3*mat1)
print('-----------')
print (mat1**2)
print('-----------')
print (mat1 + 10)

# potências em python são representas por ** , por ex., 10 elevado a 2 = 10**2

[[11 22 33]
 [ 5 10 15]
 [-1 -2 -3]]
-----------
[[33 66 99]
 [15 30 45]
 [-3 -6 -9]]
-----------
[[ 121  484 1089]
 [  25  100  225]
 [   1    4    9]]
-----------
[[21 32 43]
 [15 20 25]
 [ 9  8  7]]


In [44]:
# matriz de zeros:
zero4 = np.zeros(4)
# matriz de uns especificada com dimensões:
um5 = np.ones((4,3))
# matriz identidade:
id1 = np.eye(3)
# usando range: 
vet2 = np.arange(0,5,1)
# usando range com espaçamento:
vet3 = np.linspace(0,20,5)
# brincando com o range
vet4 = np.arange(0,10,2)

print(zero4)
print('-----------')
print(um5)
print('-----------')
print(id1)
print('-----------')
print(vet2)
print('-----------')
print(vet3)
print('-----------')
print(vet4)

[0. 0. 0. 0.]
-----------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
-----------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
-----------
[0 1 2 3 4]
-----------
[ 0.  5. 10. 15. 20.]
-----------
[0 2 4 6 8]


In [46]:
# selecionar linhas especificas de matrizes e itens específicos de vetores.

print(mat1)
print('-----------')
print(mat1[0])
print('-----------')
print(mat1[1,2] + mat1[2,2])
print('-----------')

# é possível descrever um elemento específico de matriz com MATRIZ[m,n] seguindo a mesma lógica da matemática.
# com a única exceção de que, no python, a contagem sempre começa do ZERO não do um. 

print(vet1)
print('-----------')
print(vet1[0])

[[11 22 33]
 [ 5 10 15]
 [-1 -2 -3]]
-----------
[11 22 33]
-----------
12
-----------
[11.  22.  33.5 44.  55.  66. ]
-----------
11.0


In [ ]:
# também é possível fazer operações de determinantes, matriz inversa e 
# matriz trasnposta nessa mesma biblioteca. útil pra caralho pqp. 