NumPy - MATRIZES pt.2

In [5]:
import numpy as np

# tem que rodar esse bloco para a importação funcionar. 

Vetor com valores aleatórios entre zero e um:

In [9]:
v1 = np.random.random((5))
print(v1)

[0.45419245 0.33599355 0.4243813  0.8974132  0.60833629]


Vetor com valores aleatórios entre -1 e 1:

In [10]:
v2 = np.random.randn((5))
print(v2)

[-0.33875305 -0.26945514 -0.60083864 -1.82108283  0.2359266 ]


Vetor com valores aleatórios entre -10 e 10:

In [13]:
v3 = 10*np.random.randn((5))
print(v3)

[ -5.1813797   -9.67346831 -14.77376605  12.4054264    9.06926319]


Montando uma matriz com valores aleatórios reais

In [35]:
l1 = np.random.randn((3))
l2 = np.random.randn((3))
l3 = np.random.rand((3))

m1 = np.vstack([[l1],[l2],[l3]])

print(m1)

# usar a função vstack quando quiser unir vetores em linhas para formar matriz.
# usar a função hstack quando quiser unir vetores em colunas para formar matriz.
# se só usar o np.array, ele cria um bloco de matriz que, embora pareça uma 
# matriz, não vai funcionar como uma, e vai ferrar certas operações.
# a fórmula matriz.shape entrega esse erro: out = (a,b,c) ao invés de (a,b) 
# implica nesse problema.

[[-0.61059485  0.85636942  0.3468658 ]
 [ 1.38994598  0.38177478 -1.21304676]
 [ 0.84476987  0.53254374  0.25816436]]


Separando essa matriz por linhas e colunas:

In [41]:
lin1 = m1[0,:]
lin2 = m1[1,:]
lin3 = m1[2,:]
col1 = m1[:,0]
col2 = m1[:,1]
col3 = m1[:,2]

dim = m1.shape
transp = m1.T

print(lin1)
print('-------------')
print(lin2)
print('-------------')
print(lin3)
print('-------------')
print(col1)
print('-------------')
print(col2)
print('-------------')
print(col3)
print('-------------')
print(dim)
print('-------------')
print(transp)

[-0.61059485  0.85636942  0.3468658 ]
-------------
[ 1.38994598  0.38177478 -1.21304676]
-------------
[0.84476987 0.53254374 0.25816436]
-------------
[-0.61059485  1.38994598  0.84476987]
-------------
[0.85636942 0.38177478 0.53254374]
-------------
[ 0.3468658  -1.21304676  0.25816436]
-------------
(3, 3)
-------------
[[-0.61059485  1.38994598  0.84476987]
 [ 0.85636942  0.38177478  0.53254374]
 [ 0.3468658  -1.21304676  0.25816436]]


Criando uma matriz específica com um intervalo (reshape) + Transposta (t):

In [40]:
m2 = np.arange(0,20).reshape((4,5))

print(m2)
print('-------------')

transposta = m2.T

print(transposta)

# reshape é um comamndo interessante para colocar uma série de números em 
# forma de uma matriz mais conveniente. 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
-------------
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


Criando uma matriz com condição WHERE:

In [51]:
m3 = np.random.randn(5,5)

print(m3)
print('-------------')

m4 = (m3>0)

print(m4)
print('-------------')

m5 = np.where(m4>0,1,0)

print(m5)

# associei o m4 a uma condição booleana que me retorna se minha afirmativa é 
# verdadeira ou falsa. 

# depois, a função where associa a condição verdadeira = 1 e falsa = 0.

[[ 0.47817235  0.85651328 -0.58680717 -1.59006495 -0.45119487]
 [ 0.7340688   0.39213419 -0.19485632  0.75085205  1.01448452]
 [-0.72782522 -0.56246437 -1.29525026  1.77117346 -0.78556518]
 [ 0.07703248 -0.82783786  1.51307355  0.36793521  1.03328335]
 [ 2.15255908 -0.22025437 -0.55094041  0.55946493  0.44628409]]
-------------
[[ True  True False False False]
 [ True  True False  True  True]
 [False False False  True False]
 [ True False  True  True  True]
 [ True False False  True  True]]
-------------
[[1 1 0 0 0]
 [1 1 0 1 1]
 [0 0 0 1 0]
 [1 0 1 1 1]
 [1 0 0 1 1]]
